version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    hostname: localhost
    environment:
      - MONGO_INITDB_ROOT_USERNAME=handler
      - MONGO_INITDB_ROOT_PASSWORD=handler
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://localhost:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "eventHandler1:1:1,eventHandler2:1:1"
    networks:
      - kafka-net

volumes:
  dbdata6:

networks:
  kafka-net:
    driver: bridge